title: Workspace
description: ""
baseurl: ""
url: "https://haeryu.github.io/"
theme: minima

highlighter: rouge
markdown: kramdown
color_scheme: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: ["README.md", "Gemfile", "Gemfile.lock"]

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"